version: '3.8'

services:

jenkins:

image: jenkins/jenkins:lts

container_name: jenkins

restart: unless-stopped

ports:

 - "8080:8080" # Jenkins UI

 - "50000:50000" # Jenkins agent port

volumes:

 - jenkins_data:/var/jenkins_home

environment:

 - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:

jenkins_data:
